# Model arguments
model_name_or_path: Qwen/Qwen2.5-Coder-3B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: open-r1/OpenThoughts-114k-Curated
dataset_configs:
- all
dataset_num_proc: 12

# SFT trainer config
callbacks:
- push_to_hub_revision
benchmarks:
- math_500
- aime24
- aime25
- gpqa
- lcb
bf16: true
do_eval: false
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: open-r1/Qwen2.5-Coder-3B-Instruct-SFT
hub_model_revision: v02.02
hub_strategy: every_save
learning_rate: 5.0e-07
log_level: info
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.1
packing: false
max_seq_length: 32768
max_steps: -1
num_train_epochs: 9
output_dir: data/open-r1/Qwen2.5-Coder-3B-Instruct-SFT-v02.02
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 4
push_to_hub: true
report_to:
- wandb
save_strategy: "epoch"
save_total_limit: 1
seed: 42
use_liger: true
wandb_entity: huggingface
wandb_project: open-r1
warmup_ratio: 0.03